### ISSUE TITLE
Can't terminate with keyboard shortcut

### ISSUE THREAD

**Issue by hasanavi** [Nodeclipse/www.nodeclipse.org#18]
Hi,

I'm using Eclipse Juno in Mac. I've able to run the Node JS application with cmd+shift+F11 shortcut but when I try to terminate with cmd+F2 that doesn't work. I've tried to terminate the application from eclipse menu -> Run -> Terminate but I found that is disabled.

However I was able to terminate it by clicking the Terminate button from the console view.

Is there any way to Terminate the Node JS application using keyboard shortcut?

Thanks

![screen shot 2013-06-06 at 18 03 53](https://f.cloud.github.com/assets/3259517/619349/7e166b04-cecb-11e2-810a-69d3fb93a9d3.png)

**Comment by paulvi** [comment]
Hi @hasanavi 

This repository is for web site.

Could you please copy your issue text as new issues at https://github.com/nodeclipse/nodeclipse-1/issues/

**Comment by paulvi** [comment]
@hasanavi well, I moved myself.

**Comment by hasanavi** [comment]
Thanks Paul

**Comment by paulvi** [comment]
Welcome

**Comment by tomotaro1065** [comment]
@hasanavi  Please check out https://github.com/Nodeclipse/nodeclipse-1/issues/53 .
