### ISSUE TITLE
Installation link doesn't work

### ISSUE THREAD

**Issue by mbguitarburst** [Nodeclipse/www.nodeclipse.org#58]
The provided installation link doesn't seem to work: http://marketplace.eclipse.org/marketplace-client-intro?mpc_install=759140.

When attempting to install in Eclipse, it says "no repository found".

**Comment by tomotaro1065** [comment]
This issue didn't reproduce in my environment.

What is your environment?
What operations did you do?

**Comment by mbguitarburst** [comment]
I'm actually using a build for Netsuite: SuiteCloud IDE 2.2.1 for NetSuite 2013 Release 1     

Anything I do regarding installing software throws the No repository found error.  If I go to install software it gives me the error.  If I check for updates it gives the error.  When I search for Nodeclipse it errors.

**Comment by tomotaro1065** [comment]
I'm sorry that I could not reply sooner.

I don't know about NetSuite. So I can't investigate the cause of error.
And we don't support it. 

You may try Nodeclipse on pure Eclipse version 3.7 or later.
