### ISSUE TITLE
Find partners to prolong nodeclipse.org domain registration

### ISSUE THREAD

**Issue by paulvi** [Nodeclipse/www.nodeclipse.org#62]
@lamb 你好

Time goes and nodeclipse.org domain possibly soon requires update registration.
http://www.whois.com/whois/nodeclipse.org

It is just $10 that is not big deal,
but let consider it as time to ask users and possibly find some people or organization interested in Nodeclipse that we could reference as partner.

So don't hurry, let's put some announce on www.nodeclipse.org
and wait one month.

**Comment by lamb** [comment]
OK, You can try.
