### ISSUE TITLE
Ctrl + C block the eclipse ide

### ISSUE THREAD

**Issue by iulian-dabuleanu** [Nodeclipse/www.nodeclipse.org#63]
Version 0.17
Using the CTRL-C key combination in the JS editor when nodejs server is running, the IDE is blocked for long time and become non responsive.

**Comment by paulvi** [comment]
This is note related to web site content www.nodeclipse.org

This is known issue with JSDT, search on Stackoverflow.

And try with newer Enide 2015

**Comment by paulvi** [comment]
open on https://github.com/nodeclipse/nodeclipse-1/ if you want to continue conversation

BTW since Nodeclipse 1.0 JSDT nature is disabled by default in new projects

ref https://github.com/Nodeclipse/nodeclipse-1/issues/159
