### ISSUE TITLE
NodeClipse only allows debugging of 1 .js file at a time

### ISSUE THREAD

**Issue by rapiddata** [Nodeclipse/www.nodeclipse.org#64]
NodeClipse only allows debugging of 1 .js file
If I set a breakpoint in a different .js file the breakpoint is never hit.
Error is source is not available.
NodeClipse is not able to load source of different files in the debug stack.
Maybe because I am running Current Version: v0.12.0 of Node.js because it used to work with an earlier version of Node.js.
I am also running Eclipse Luna SR2 on Windows 7.

**Comment by paulvi** [comment]
closing as duplicate of https://github.com/Nodeclipse/nodeclipse-1/issues/189

besides it anyways should be in https://github.com/Nodeclipse/nodeclipse-1/issues/

try Nodeclipse 1.x with Node 4.x
